spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/booster?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: rootpw

  jpa:
    hibernate:
      ddl-auto: update # prod validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_ID}
    password: ${GOOGLE_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
